---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
      app: application
      spec:
        containers:
          - name: application
            image: docker-registry/image:tag
            ports:
              - containerPort: 8080
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 1000m
                memory: 500Mi
              requests:
                cpu: 500m
                memory: 200Mi
            envFrom:
              - secretRef:
                  name: application-secret
              - configMapRef:
                  name: application-config
        imagePullSecrets:
          - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: application
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: application
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: application-ingress
  annotations:
    kubernetes.io/ingress.class: nginx-internal
spec:
  tls:
    - hosts:
        - application.kube.dns.com
  rules:
    - host: application.kube.dns.com
      http:
        paths:
          - backend:
              serviceName: application
              servicePort: 8080
