---
apiVersion: v1
kind: Secret
metadata:
  name: some-secret
  namespace: default
type: Opaque
stringData:
  SECRET_ONE: ${SECRET_ONE}
  SECRET_TWO: ${SECRET_TWO}
  SECRET_THREE: ${SECRET_THREE}

---

# Get output of secret without external tools
# kubectl get secret some-secret -o go-template='{{range $k,$v := .data}}{{"### "}}{{$k}}{{"\n"}}{{$v|base64decode}}{{"\n\n"}}{{end}}'
